### ISSUE TITLE
bridges server should return 404 on missing assignment

### ISSUE THREAD

**Issue by esaule** [squeetus/bridgesAPI#26]
When accessing an assignment through the assignment JSON endpoint, the server returns 500 Internal Server Error if the assignment does not exist. It should return 404 Object not found. 

For instance, 
wget http://bridges-cs.herokuapp.com/assignmentJSON/106156.00/bridges_workshop
gets 500 Internal Server Error.

I think it should return 404 Not Found.
That would make error messages from the client's perspective easier to understand.

**Comment by squeetus** [comment]
This should be addressed here https://github.com/squeetus/bridgesAPI/commit/efec56aa65cc0ad9d93d68249487432991ffbecd.
