### ISSUE TITLE
New Tree types..

### ISSUE THREAD

**Issue by krs-world** [squeetus/bridgesAPI#27]
Did try the Kdtree example, but not able to see the node-link visualization..  Heres  the JSON
{"visual":"KdTree","title":"A Kd Tree Example","description":"","map_overlay":false,"coord_system_type":"cartesian","nodes":{"color":[255,0,0,1.000000],"shape":"circle","size":10,"name":"","key":"50","dimension":"0","thickness":"0","children":[{"linkProperties":{"color":[70,130,180,1.000000],"thickness":1,"weight":1},"color":[255,165,0,1.000000],"shape":"circle","size":10,"name":"","key":"25","dimension":"1","thickness":"0","children":[{"linkProperties":{"color":[70,130,180,1.000000],"thickness":1,"weight":1},"color":[70,130,180,1.000000],"shape":"circle","size":10,"name":"","key":"20","dimension":"0","thickness":"0","children":[{"name":"NULL"},{"name":"NULL"}]},{"linkProperties":{"color":[70,130,180,1.000000],"thickness":1,"weight":1},"color":[255,165,0,1.000000],"shape":"circle","size":10,"name":"","key":"30","dimension":"0","thickness":"0","children":[{"name":"NULL"},{"name":"NULL"}]}]},{"linkProperties":{"color":[70,130,180,1.000000],"thickness":1,"weight":1},"color":[70,130,180,1.000000],"shape":"circle","size":10,"name":"","key":"75","dimension":"1","thickness":"0","children":[{"linkProperties":{"color":[70,130,180,1.000000],"thickness":1,"weight":1},"color":[255,165,0,1.000000],"shape":"circle","size":10,"name":"","key":"60","dimension":"0","thickness":"0","children":[{"name":"NULL"},{"name":"NULL"}]},{"linkProperties":{"color":[70,130,180,1.000000],"thickness":1,"weight":1},"color":[255,165,0,1.000000],"shape":"circle","size":10,"name":"","key":"80","dimension":"0","thickness":"0","children":[{"name":"NULL"},{"name":"NULL"}]}]}]}}

**Comment by squeetus** [comment]
'KdTree' has been added to the server as a valid assignment type, mapping to 'tree' vistype.
