### ISSUE TITLE
Shape collection --

### ISSUE THREAD

**Issue by krs-world** [squeetus/bridgesAPI#28]
I think we need unfilled shapes  - I would suggest taking in a fill color of "none"  as one way to do it;  I also tried setting opacity to  a low value, this didnt seem to have no effect.

Basically, I am trying to draw the kdt tree partitioning lines, but this gets masked by the initial filled rectangle.

We probably need to also specify a rectangle, using a lower left corner and size  - maybe client side to support this?

**Comment by squeetus** [comment]
Addressed in https://github.com/squeetus/bridgesAPI/commit/490ae9d2972061a1e20ece10a12e132395799f80. 

By default, shapes will be unfilled with a small black border.
