### ISSUE TITLE
Shapes..

### ISSUE THREAD

**Issue by krs-world** [squeetus/bridgesAPI#29]
I tried drawing two shapes next to each other:

Symbol *s2 = new Symbol("rectangle");
    s2->setColor(Color("red"));
    s2->setStrokeColor(Color("magenta"));
    s2->setSize(100,100);
    s2->setLocation(0, 0);
    sc->addSymbol(s2);

    Symbol *s3 = new Symbol("rectangle");
    s3->setColor(Color("red"));
    s3->setStrokeColor(Color("magenta"));
    s3->setSize(100, 100);
    s3->setLocation(50, 0);

    sc->addSymbol(s3);

This produces two shapes widely separated in X. That doesnt make sense. The rectangles are 100x100 and the second one is a (50,0); so it should be right adjacent to each other.

David?

**Comment by krs-world** [comment]
Adjacent to the first one, with no gap.

**Comment by squeetus** [comment]
Addressed in https://github.com/squeetus/bridgesAPI/commit/490ae9d2972061a1e20ece10a12e132395799f80.

Added a scale factor based on the rescaled dimensions of the visualization to modify shape sizes.
