### ISSUE TITLE
OSM graph

### ISSUE THREAD

**Issue by squeetus** [squeetus/bridgesAPI#36]
for large graphs, use a slim version of the graph representation. Perhaps graph-canvas, or largeGraph or something for vistype. 

Use vertex buffers, perform transforms in shader (using scale translate as uniforms). Client will still pass an array of vertices (tuples of lat, long) and edges (indexed into vertex list) with a byte color. 

No interaction or zoom/pan, just draw once?

**Comment by esaule** [comment]
@squeetus did you push anything to the clone server to support this? Or did you just develop locally so far?
(looping @krs-world )

**Comment by squeetus** [comment]
@esaule I haven't pushed anything yet, and the code itself is still pretty rudimentary. On Friday we mentioned passing these things as line segments (5-tuples of x, y, x2, y2, color). What is the current status on the data format?

**Comment by krs-world** [comment]
I have it producing JSON in our regular format of 'nodes: [lat, long, 
color], 'links': [src, target, color].  This can be changed, but wil 
probably save little - we do need color for nodes and links. With the 
filtering the of the data we are not implementing, it might be 
sufficient. But easy to change..

Also I should have a webgl example of the data with zooming hopefully by 
end of day. You can try to then integrate that into the server side.

     - krs

**Comment by esaule** [comment]
So, we noticed somethings on the graph-canvas visualization that could be worth adjusting.

In this file: https://github.com/squeetus/bridgesAPI/blob/master/public/js/graph-canvas.js

line 58 performs a split on d.name, we could test the existence of
d.name and set d.lines at "" or whatever is appropriate [""] ?

The parameters d.shape and d.size were meant to be optional as is
understood by looking at BridgesVisualizer.shapeLookup or by looking
at line 62.

When drawing links with drawCurvedLink, the computation of d2 uses
d.target.size. If size was undefined line 62, I guess it is still
undefined there, which probably causes shapeedge to return 0 or
undefined and cause a division by 0, or something else of equally bad
consequence.

I don't exactly know how javascript works, when you dereference
something that does not exist as a function parameter. But I suggest
that all the functions in
https://github.com/squeetus/bridgesAPI/blob/master/public/js/Bridges/BridgesVisualizer.js
about scaling and ragning and what not test the parameter and if it is
undefined return a sane default value.

**Comment by squeetus** [comment]
I will take a look at the graph-canvas stuff @esaule mentioned at a future point. I think some of the attributes in question are getting populated with defaults somewhere, but we may be making some assumptions about what the data will contain. I will move that discussion to a new issue. 

I have pushed some webgl changes to the Bridges Clone server now though, so if you have an OSM client program you want to test you should be able to do so. Just make sure you point your code to the clone:
`Bridges->setServer('clone')`

If in your testing you notice any strangeness or potential bugs, please make an issue and let me know.
